### ISSUE TITLE
Error with file download: tutorial ~R/AIS-data/AIS-QF-tutorial/download-NEON-AIS-data/download-NEON-AIS-data.R

### ISSUE THREAD

**Issue by natalie-robinson** [NEONScience/NEON-Data-Skills#613]
The API download call on line 22 is returning:

NEON.D11.PRIN.DP1.20288.001.2020-02.expanded.20220120T173946Z.RELEASE-2022.zip could not be downloaded. Re-attempting.

NEON.D11.PRIN.DP1.20288.001.2020-02.expanded.20220120T173946Z.RELEASE-2022.zip could not be downloaded. URLs may have expired. Refreshing URL list.

Refresh did not solve the isse. URL query for file NEON.D11.PRIN.DP1.20288.001.2020-02.expanded.20220120T173946Z.RELEASE-2022.zip failed. If all files fail, check data portal (data.neonscience.org/news) for possible outage alert.

**Comment by cklunch** [comment]
@glitt13 @bhensley0440

**Comment by cklunch** [comment]
@natalie-robinson This error is about the .zip files, which we don't use anymore, so it may not be the tutorial that's the issue. What version of neonUtilities are you testing with? Should be 2.1.3 now.

**Comment by cklunch** [comment]
@natalie-robinson I'm not able to replicate the error. Is it still happening on your end?

**Comment by cklunch** [comment]
@natalie-robinson @glitt13 @bhensley0440
Eric ran into this same problem in a different context, and we determined it's because of the token in the function call. If you don't have an environment variable with that name, it returns an empty string, which the NEON API doesn't like. If you give the API an invalid token, it treats the request as if there is no token, but an empty string fails.

I'll be updating neonUtilities to work around this, so it should be resolved when the next version goes out. If you want to fix it in the meantime, just drop the token from the tutorial.

**Comment by cklunch** [comment]
Update to neonUtilities 2.1.4 included smooth handling for this situation. But also, don't reference environment variables that don't exist.
